app = "bettys-bomb-tracker"
primary_region = "bom"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8501"

[[services]]
  internal_port = 8501
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[mounts]]
  source = "data"
  destination = "/app/data"
  initial_size = "1gb"
